### ISSUE TITLE
Cassandra sink configuration

### ISSUE THREAD

**Issue by nurgasemetey** [spring-cloud/spring-cloud-stream-modules#261]
Hello guys,
I patched pre-built Cassandra Sink application and when I added the following line:

````yml
spring:
  data:
      cassandra:
        keyspace-name:
````
It complained that there is no keyspace named `tmp`. I found the following line:

https://github.com/spring-cloud/spring-cloud-stream-modules/blob/master/cassandra-sink/src/main/java/org/springframework/cloud/stream/module/cassandra/CassandraProperties.java#L53

Why `spring.application.name` is used for keyspace name?
